### GET request to Calculator
GET http://localhost:7071/api/calculator
Accept: application/json

###

### POST request to Calculator
POST http://localhost:7071/api/calculator
Content-Type: application/json

{
    "name": "TestUser"
}